version: '3.7'
services:
  todo-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'todo-app'
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev"
        ports:
            - 9500:9500